### PR TITLE
EN-7200 - Allow overriding the METRICS_DIR

### PR DESCRIPTION
**Pull request by raganw**
Allow overriding the METRICS_DIR via METRICS_DIR_OVERRIDE

### CODE REVIEW

**Comment by hatmatter** [comment]
If this change is committed it should also be added to runit/set_metrics_dir so I added that

**Comment by rantler** [comment]
Seems legit. What can we expect `$METRICS_DIR_OVERRIDE` to be when it's provided?

**Comment by jhaynes** [comment]
We will probably use something like `/data/metrics`. But the issue here was that we need to know what it is in advance to map it outside the container for `metrics-consumer` to use. (in aws we have `balboa-agent` running on each mesos hosts that knows how to handle this). 

Right @raganw ?

**Comment by znep** [comment]
Last I knew on Friday, we _think_ we don't need this because metrics
consumer actually does handle subdirectories.  But it wasn't tested end to
end.

**Comment by raganw** [comment]
Closing as it was determined to not be necessary.

**Pull request closed without merging**
