### PR TITLE
NO-JIRA: Use apt and an official repository to install node 10

### PR DESCRIPTION
**Pull request by am2000**

### CODE REVIEW

**Comment by am2000** [comment]
@JoeNunnelley: huh, it does say that, but there is a node 10 package on trusty:

```root@9d9f72d970de:/# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
root@9d9f72d970de:/# dpkg -l nodejs
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                  Version                         Architecture                    Description
+++-=====================================================-===============================-===============================-===============================================================================================================
ii  nodejs                                                10.14.0-1nodesource1            amd64                           Node.js event-based server-side javascript engine
```

**Comment by znep** [comment]
If this is an issue and you are adventurous you could try switching it to the `socrata/bionic-runit` base image.

No idea if it works as the runit image is kinda complicated compared to the non-runit image and I could foresee various init related issues, but it is an option to try.  We don't have any evidence to think 18.04 containers won't run fine on 14.04 docker hosts.  Eventually everything will have to be updated, but we aren't prioritizing it in general until we are done with the hosts.

**Comment by am2000** [comment]
@znep Oh, that's good to know. For now I think we're good with 14 but I will keep that in mind.

**Comment by znep** [comment]
Hmm, 10.14.0 isn't the current release.

**Pull request merged**
