### PR TITLE
EN-19059: Remove bundler tag. Correct tag in ruby/2.3-admin.

### PR DESCRIPTION
**Pull request by housepage**

### CODE REVIEW

**Comment by socrata-pull-request-updater** [comment]
This PR should be reviewed by: @socrata/missioncontrol

**Comment by housepage** [comment]
Because in order to a native install of some gems, Hermes needs build-essential and some other apt packages installed. It needs to happen at the top of the Dockerfile and running `RUN` invalidates the Docker cache for any subsequent commands in a Dockerfile. Therefore, it exists as an intermediate step so that building a Hermes docker image doesn't always run `apt-get update && apt-get install` every single it builds.

**Comment by michaelb990** [comment]
Did we figure out how to "unf### bundler"?

https://github.com/socrata/shipyard/commit/ea93e826ce9a6d6d9f4899bd333f6c9ef15d802b

**Comment by housepage** [comment]
@michaelb990 After talking with Chui, he thought we could unpin it safely and that it broke the frontend build in a very obvious and repeatable way when it was fucked. I've also been able to build the frontend docker image locally. I will check in after this is merged to make sure the frontend docker image build succeeds.

**Pull request merged**
