### PR TITLE
Add ruby 2.5.3

### PR DESCRIPTION
**Pull request by smooshy**

### CODE REVIEW

**Comment by smooshy** [comment]
Hmm. Failing to build locally with the checksum found on https://www.ruby-lang.org/en/downloads/. Thoughts?

**Comment by znep** [comment]
Woah that is a heck of a dockerfile... hard to debug with everything chained into one giant run command.

Anyway, looks like you grabbed the one for the `gz` not the `xz`...

**Comment by JoeNunnelley** [comment]
compiled it and it failed :  ruby.tar.xz: FAILED. so see marc's point above.

**Comment by smooshy** [comment]
D'oh! Yeah. I just copied 2.5.0 and updated a few of the constants.

**Comment by JoeNunnelley** [comment]
the runit-ruby one worked. the ruby one failed...

**Comment by smooshy** [comment]
@JoeNunnelley that's a little scary that if worked the second time because the sha shouldn't match... I just pushed a commit that uses the correct sha.

**Comment by smooshy** [comment]
Tested building both locally with new checksum SHA and they worked.

**Pull request merged**
