### PR TITLE
Move rails3-deps up to root of shipyard

### PR DESCRIPTION
**Pull request by smooshy**
Trying to add some sanity to base-image building... Maybe this will help with a race condition between rails3-deps and ruby1.9

### CODE REVIEW

**Comment by michaelb990** [comment]
Update the readme while you're at it :+1: 

Let's verify that we've fixed the frontend build before you merge, but lgtm.

**Comment by raganw** [comment]
I think you'll need to update this item in Docker Hub so that it continues to build automatically. Check with Ops on that.

**Comment by michaelb990** [comment]
Also, I'll have to update docker hub when you merge.

**Comment by michaelb990** [comment]
What @raganw said. I will do it.

**Pull request merged**
