### PR TITLE
Ruby on Ubuntu 18.04

### PR DESCRIPTION
**Pull request by iamjohnnym**
Added various Dockerfile's for Ruby on 18.04.

Ruby 2.5.0, 2.5.3, 2.6.1, and 2.6.3

### CODE REVIEW

**Comment by iamjohnnym** [comment]
I'm not a huge fan of this commit.  I _really_ want to explore a better way of building our images.

**Comment by znep** [comment]
What if we only supported ruby 2.6.5 (the latest IIRC) on 18.04 and just had people update their app to use 2.6.5 as part of updating it to 18.04?

**Comment by JoeNunnelley** [comment]
I'd support 2.5.3 and 2.6.5 out of the gate just since its unlikely everyone will convert all at once.

**Comment by znep** [comment]
@JoeNunnelley Are there known blockers preventing projects from upgrading to 2.6?  If there aren't, it seems to me that for most things if you are going to go through the work and testing to upgrade to bionic then slipping a ruby upgrade in at the same time makes sense, unless there are additional complexities there.  If that is a big lift for some project for some reason, then we could backfill a 2.5 version later.

**Comment by iamjohnnym** [comment]
After talking about this with Marc, I agree with the move to only include `2.6.5`, the current latest. Doing so will hopefully encourage others to use this image over lesser version'd ruby images.  If there's a need for lesser versions, we can revisit the subject then.

**Pull request merged**
